services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo-data:/data/db
  application:
    build: .
    container_name: application
    ports:
      - "5000:5000"
    environment:
      MONGO_USERNAME: root
      MONGO_PASSWORD: example
      MONGO_HOST: mongo
      MONGO_PORT: 27017
      BG_COLOR: teal
    depends_on:
      - mongo

volumes:
  mongo-data:

